### ISSUE TITLE
Maven release

### ISSUE THREAD

**Issue by ircca** [maiha/gatling-amqp#1]
Your project looks very promising and we would like to use it in our performance tests, especially the part of consuming messages.

Is it possible to create a maven release in maven central? 

Thx.

**Comment by maiha** [comment]
Hi, birynk.
I'm grad you like this project.
I requested maven central repository today. Please wait a few days!

maiha

**Comment by ircca** [comment]
Great, thx.

**Comment by jitpack-io** [comment]
Btw, maybe this will help in the mean time https://jitpack.io/#maiha/gatling-amqp/0.4 : )
