### ISSUE TITLE
One consumer per scenario

### ISSUE THREAD

**Issue by ircca** [maiha/gatling-amqp#5]
Hi, 

Is there a way to define just one consumer for a scenario which spans more than one user? I have a scenario which publishes messages concurently and would like to have just one consumer to see its throughput.

birynk

**Comment by maiha** [comment]
Sorry, no ways. In this version, connections are created same number as user sessions.

**Comment by ircca** [comment]
Ok, thx. Are you planning to provide such a feature in the near future?

**Comment by maiha** [comment]
no plans. sorry...
